### ISSUE TITLE
Change all `hiperta_*` to `hipecta_*` 

### ISSUE THREAD

**Issue by garciagenrique** [vuillaut/LST_scripts#15]
Misleading.

**Comment by vuillaut** [comment]
> Misleading.

Is it?

It depends on what library is used.

**Comment by garciagenrique** [comment]
In my opinion we should call correctly (myself the first one ! :-D ) things by how they were defined. `hipecta_*` it should be Real-Time stuff. As we are using a wrapped version of the code in C++ (HiPeRTA), this is (unless I'm wrong) a HiPeCTA code.

**Comment by garciagenrique** [comment]
Indeed, after talking with Pierre, the "entry point" `hiperta_r1_to_dl1` is not an entry point but the call of binaries. So indeed we are not wrapping nothing. Sorry for the mess.
