### ISSUE TITLE
redundant libraries

### ISSUE THREAD

**Issue by garciagenrique** [vuillaut/LST_scripts#30]
why using `from lstchain.io.data_management import *` when the `data_management` library of the LST_scripts repo is going to be used anyway ? 
Just in case I'm loosing a point - can this be modified so that only the library from LST_scripts is used ?

**Comment by vuillaut** [comment]
I think it's done that way only for historical reasons, when there were only *scripts* in LST_scripts and function needs to be imported from somewhere.
In any case, yes, we should be the library self-consistent if possible.

**Comment by garciagenrique** [comment]
Resolved in #31
