### ISSUE TITLE
dl2 training and testing share the same `*.o` and `*.e` files

### ISSUE THREAD

**Issue by garciagenrique** [vuillaut/LST_scripts#36]

**Comment by garciagenrique** [comment]
If both jobs are sbatched/processed at the same time - what it should normally happen -  both outputs/errors will be written in the same file.

**Comment by garciagenrique** [comment]
Comments @vuillaut ? Otherwise it will be left like this for the moment.

**Comment by vuillaut** [comment]
feel free to improve if you have the opportunity, not a priority right now
