### ISSUE TITLE
`n_files_per_dl1` not working as intended

### ISSUE THREAD

**Issue by vuillaut** [vuillaut/LST_scripts#48]
I think the intention was to do:
`r0_to_dl1 list_of_r0` with `len(list_of_r0) = n_files_per_dl1` and get a single merged dl1.
At least this is what the name suggests.

The way it works right now rather corresponds to a `n_files_per_job` - but we still get 1 dl1 file for each r0 file and then merged them.

To be discussed and corrected.

**Comment by garciagenrique** [comment]
The functioning of the code was not changed at any time, i.e., it has been like this from the very first beginning. 

However, I completely agree with your comment, meaning that I will be willing to change its way of working at any time !

**Comment by vuillaut** [comment]
> The functioning of the code was not changed at any time, i.e., it has been like this from the very first beginning.

I know :)

> However, I completely agree with your comment, meaning that I will be willing to change its way of working at any time !

Small, not urgent, improvements. TBD when there is nothing else.

**Comment by garciagenrique** [comment]
Will be improved very soon, really not working.

**Comment by garciagenrique** [comment]
The argument name and how it is working has changed. Solved by #70 .
