### ISSUE TITLE
Bug checking merge_and_copy_dl1 jobs

### ISSUE THREAD

**Issue by garciagenrique** [vuillaut/LST_scripts#69]
launching both `prod5` and `prod5_trans_80` pipeline, there is a test that is triggered.

Found why and correct it, as it should not check this (not this way at least)

```
There are errors in the following log files:
 ['job27_test.e', 'job21_train.e', 'job29_test.e', 'job41_train.e', 'job24_train.e', 'job25_test.e', 'job23_test.e', 'job6_test.e', 
'job18_train.e', 'job18_test.e', 'job17_train.e', 'job30_train.e', 'job22_train.e', 'job37_test.e', 'job5_test.e', 'job42_test.e', 
'job39_train.e', 'job37_train.e', 'job30_test.e', 'job45_train.e', 'job1_test.e', 'job17_test.e', 'job43_test.e', 'job49_train.e', 
'job20_train.e', 'job34_test.e', 'job42_train.e', 'job32_test.e', 'job3_train.e', 'job9_train.e', 'job36_test.e', 'job47_test.e', 
'job49_test.e', 'job11_test.e', 'job35_train.e', 'job45_test.e', 'job16_train.e', 'job7_train.e', 'job23_train.e', 'job46_test.e', 
'job26_test.e', 'job40_test.e', 'job43_train.e', 'job10_train.e', 'job13_test.e', 'job47_train.e', 'job32_train.e', 'job20_test.e', 
'job25_train.e', 'job16_test.e', 'job14_test.e', 'job39_test.e', 'job15_train.e', 'job40_train.e', 'job7_test.e', 'job4_test.e', 
'job2_test.e', 'job10_test.e', 'job27_train.e', 'job3_test.e', 'job15_test.e', 'job5_train.e', 'job0_test.e', 'job12_test.e', 'job44_test.e', 
'job28_train.e', 'job0_train.e', 'job4_train.e', 'job33_train.e', 'job41_test.e', 'job34_train.e', 'job31_test.e', 'job21_test.e', 
'job24_test.e', 'job48_test.e', 'job19_test.e', 'job8_train.e', 'job38_train.e', 'job44_train.e', 'job1_train.e', 'job36_train.e', 
'job13_train.e', 'job35_test.e', 'job19_train.e', 'job33_test.e', 'job9_test.e', 'job28_test.e', 'job26_train.e', 'job31_train.e', 
'job22_test.e', 'job38_test.e', 'job48_train.e', 'job2_train.e', 'job29_train.e', 'job6_train.e', 'job14_train.e', 'job11_train.e', 
'job46_train.e', 'job8_test.e', 'job12_train.e']
 Are you sure you want to continue? [y/N]

```

**Comment by vuillaut** [comment]
That's because there are Error messages in these logs

**Comment by garciagenrique** [comment]
The trigger of the message is not an error (at least an error that makes fail the pipeline), rather a warning. I checked long time ago, it's not a new issue, although might be misleading for users

**Comment by garciagenrique** [comment]
The first stage of `merge_and_copy` searches for the string `Error` in any line of the `r0_to_dl1` logs.

It finds:
> WARNING: CacheMissingWarning: Remote data cache could not be accessed due to FileNotFound**Error**: [Errno 2] No such file or directory: '/local/home/lstanalyzer/.astropy' [astropy.utils.data]
WARNING: failed to download ftp://anonymous:mail%40astropy.org@gdc.cddis.eosdis.nasa.gov/pub/products/iers/finals2000A.all and https://datacenter.iers.org/data/9/finals2000A.all, using local IERS-B: <urlopen error Unable to open any source! Exceptions were {'ftp://anonymous:mail%40astropy.org@gdc.cddis.eosdis.nasa.gov/pub/products/iers/finals2000A.all': URL**Error**("ftp error: timeout('timed out')"), 'https://datacenter.iers.org/data/9/finals2000A.all': URL**Error**(timeout('timed out'))}> [astropy.utils.iers.iers]

thus not a "real" error
